services:
  - type: web
    name: kashi-ganga-aarti-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn kashi_ganga.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: kashi-ganga-aarti-app.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: WHATSAPP_NUMBER
        value: "919235054005"
      - key: DATABASE_URL
        sync: false
