# Generated by Django 4.2.29 on 2026-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding Ganga Aarti"),
                            ("birthday", "Birthday Aarti"),
                            ("anniversary", "Anniversary Aarti"),
                            ("spiritual", "Spiritual Ceremonies"),
                            ("ganga_aarti", "Ganga Evening Aarti Experience"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service Review",
                "verbose_name_plural": "Service Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
